- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
    state: present
  become: true

- name: Add Jenkins repository
  apt_repository:
    repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
    state: present
  become: true

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes
  become: true

- name: Ensure Jenkins service is running
  service:
    name: jenkins
    state: started
    enabled: true 
  become: true   

