---
    - name: Check the /tmp directory exists on EC2
      file:
        path: /tmp
        state: directory

    - name: Download oc CLI on EC2
      get_url:
        url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz
        dest: /tmp/openshift-client-linux.tar.gz
        mode: '0644'

    - name: Copy oc CLI to Jenkins container
      command: docker cp /tmp/openshift-client-linux.tar.gz jenkins:/tmp/openshift-client-linux.tar.gz

    - name: Extract oc CLI 
      command: docker exec -u 0 jenkins tar -zxvf /tmp/openshift-client-linux.tar.gz -C /usr/local/bin

    - name: Make oc CLI Executable
      command: docker exec -u 0 jenkins chmod +x /usr/local/bin/oc

