- name: "sysctl -w vm.max_map_count=262144"
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    sysctl_set: yes

- name: Create Docker volumes for SonarQube
  command: docker volume create {{ item }}
  with_items:
    - sonarqube_data
    - sonarqube_logs
    - sonarqube_extensions
    - postgresql
    - sonarqube_conf

- name: Pull PostgreSQL image from Dockerhub
  docker_image:
    name: postgres
    tag: "13"
    source: pull

- name: Run PostgreSQL container inside EC2
  docker_container:
    name: sonarqube_db
    image: postgres:13
    state: started
    restart_policy: always
    env:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql:/var/lib/postgresql/data
    cpus: 1
    memory: 2g

- name: Pull SonarQube image from Dockerhub
  docker_image:
    name: sonarqube
    tag: "latest"
    source: pull

- name: Run SonarQube container inside EC2
  docker_container:
    name: sonarqube
    image: sonarqube:latest
    state: started
    restart_policy: always
    env:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    links:
      - sonarqube_db
    cpus: 2
    memory: 4g

