apiVersion: v1
kind: Service
metadata:
  name: grad-project-service
spec:
  selector:
    app: grad-project
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
      
